federation_version: =2.3.0
subgraphs:
  products:
    routing_url: http://localhost:4009/

    schema:
      file: ../products/products.graphql
  reviews:
    routing_url: http://localhost:4008/

    schema:
      file: ../reviews/reviews.graphql
